export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const IS_LOADING = 'IS_LOADING';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SET_RECEIPT = 'SET_RECEIPT';
export const TRANSACTION_LOADING = 'TRANSACTION_LOADING';
